version: '3'
services:
  drop_prisma:
    container_name: drop-prisma
    image: prismagraphql/prisma:1.31
    restart: always
    ports:
      - "4467:4467"
    environment:
      PRISMA_CONFIG: |
        port: 4467
        databases:
          default:
            connector: postgres
            host: drop_db
            port: 5432
            user: prisma
            password: prisma
  drop_db:
    container_name: drop_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
